export const FETCH_GAMES_REQUEST = "FETCH_GAMES_REQUEST";
export const FETCH_GAMES_SUCCESS = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAILURE = "FETCH_GAMES_FAILURE";

export const FETCH_POPULAR_GAMES_REQUEST = "FETCH_POPULAR_GAMES_REQUEST";
export const FETCH_POPULAR_GAMES_SUCCESS = "FETCH_POPULAR_GAMES_SUCCESS";
export const FETCH_POPULAR_GAMES_FAILURE = "FETCH_POPULAR_GAMES_FAILURE";

export const FETCH_FILTERED_GAMES_REQUEST = "FETCH_FILTERED_GAMES_REQUEST";
export const FETCH_FILTERED_GAMES_SUCCESS = "FETCH_FILTERED_GAMES_SUCCESS";
export const FETCH_FILTERED_GAMES_FAILURE = "FETCH_FILTERED_GAMES_FAILURE";

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";

export const SET_SEARCH_QUERY = "SET_SEARCH_QUERY";
export const CLEAR_SEARCH_QUERY = "CLEAR_SEARCH_QUERY";
